spack:
  config:
    install_tree:
      root: $env/install
    deprecated: true
  modules:
    default:
      roots:
        lmod: $env/install/modulefiles

  view: false
  include:
  - site
  concretizer:
    unify: true

  specs:
    - netcdf-fortran
    - nccmp
    - nco
    - ncview@2.1.9
